### ISSUE TITLE
Spring Cloud Gateway를 사용한 가중치 기반 로드밸런싱 설정 파일 백업

### ISSUE THREAD

**Issue by hyunsb** [hyunsb/msa-order-management#5]
```yaml
server:
  port: 19091

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: product-service-1
          uri: lb://product-service
          predicates:
            - Path=/products/**
            - Weight=group-product, 7

        - id: product-service-2
          uri: lb://product-service
          predicates:
            - Path=/products/**
            - Weight=group-product, 3

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**

      discovery:
        locator:
          enabled: true

    loadbalancer:
      enabled: true
      configurations: weighted

service:
  jwt:
    secret-key: 

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
```
